### ISSUE TITLE
All goals should have skip parameter to skip execution

### ISSUE THREAD

**Issue by robertpatrick** [kordamp/oci-maven-plugin#4]
I would like to use the `get-object` and `put-object` goals but I need to be able to make their execution triggered by a build property value.  Typically, this is accomplished by the goal having a `skip` configuration parameter that defaults to `false` and will skip execution when its value is set to `true`.

**Comment by robertpatrick** [comment]
@aalmiray Thanks!  Any sense when the next release will be so that we can pick up this change?

**Comment by aalmiray** [comment]
Already released `0.5.0` with this change 😄
