### ISSUE TITLE
Convert patronage message from Warning to Info

### ISSUE THREAD

**Issue by robertpatrick** [kordamp/oci-maven-plugin#8]
We regularly scan our builds to address and remove all warnings.  While I appreciate your desire to have people sponsor the plugin, making this a build warning is problematic for us.  Can you please provide some way to squelch this warning?

**Comment by aalmiray** [comment]
The banner appears at most 3 times at any given machine as long as caches are retained that is, `~/.m2/caches/kordamp`.

**Comment by robertpatrick** [comment]
Unfortunately, that doesn't help with our Jenkins builds where we are spinning up Docker containers to run the build.

**Comment by aalmiray** [comment]
Banner output moved to info. it can also be skipped by setting a `org.kordamp.banner` System property to `false`.
